# Generated by Django 6.0.2 on 2026-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='inr', max_length=10),
        ),
    ]
