# Generated by Django 6.0.2 on 2026-02-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
